version: "3.3"
services:
  travelwebsite-db:
    container_name: travelwebsite-mysql-db
    image: jamielsharief/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "travelwebsite_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-travelwebsite-db:/var/lib/mysql
volumes:
  vol-travelwebsite-db:
